---
Name: tomstgeorge-silverstripe-wordpress-logins
Before: '#modelascontrollercatchallroute'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: '%$TomStGeorge\SilverStripeWordpressLogins\Authenticator\WordPressAuthenticator'

SilverStripe\Security\MemberAuthenticator\LoginHandler:

  extensions:
    - TomStGeorge\SilverStripeWordpressLogins\Extension\LoginHandlerExtension

SilverStripe\Security\MemberAuthenticator\LogoutHandler:
  extensions:
    - TomStGeorge\SilverStripeWordpressLogins\Extension\LogoutHandlerExtension

SilverStripe\Security\Member:
  extensions:
    - TomStGeorge\SilverStripeWordpressLogins\Extension\MemberPasswordSyncExtension

---
Name: tomstgeorge-silverstripe-wordpress-logins-middleware
---
SilverStripe\Core\Injector\Injector:
  SSWPAutoLoginMiddleware:
    class: TomStGeorge\SilverStripeWordpressLogins\Middleware\SSWPAutoLoginMiddleware
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        SSWPAutoLoginMiddleware: '%$SSWPAutoLoginMiddleware'

SilverStripe\Control\Director:
  rules:
    'silverstripe-auth': 'TomStGeorge\SilverStripeWordpressLogins\Controller\AuthController'
    'silverstripe-auth/$Action': 'TomStGeorge\SilverStripeWordpressLogins\Controller\AuthController'
    'silverstripe-auto-login': 'TomStGeorge\SilverStripeWordpressLogins\Controller\AutoLoginController'
    'silverstripe-auto-logout': 'TomStGeorge\SilverStripeWordpressLogins\Controller\AutoLogoutController'

